name: Diabet

on:
  workflow_dispatch:

jobs:
  download-dataset-processing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2
      - name: Install Kaggle API
        run: pip install kaggle
      - name: Download dataset from Kaggle
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          kaggle datasets download -d akshaydattatraykhare/diabetes-dataset
          unzip -o diabetes-dataset.zip
      - name: Upload CSV files as artifact - 1
        uses: actions/upload-artifact@v3.1.2
        with:
          name: csv-files
          path: |
            *.csv
      - name: Install Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.9
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r reg.txt
      - name: Preprocessing
        run: |
          python test.py
  Learn-and-save-models:
    needs: download-dataset-processing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2
      - name: Download artifact - 1
        uses: actions/download-artifact@v3.0.2
        with:
          name: csv-files
      - name: Install Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.9
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r reg.txt
      - name: Learn and Save
        run: |
          python learn_model.py
      - name: Upload a Build Artifact - 2
        uses: actions/upload-artifact@v3.1.2
        with:
          name: save_models_info_metrics
          path: |
            result.txt
            last_10_rows.csv
            model_LR.joblib
            model_RF.joblib
  Test_models:
    needs: Learn-and-save-models
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2
      - name: Download artifact - 2
        uses: actions/download-artifact@v3.0.2
        with:
          name: csv-files
      - name: Download artifact - 3
        uses: actions/download-artifact@v3.0.2
        with:
          name: save_models_info_metrics
      - name: Install Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.9
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r reg.txt
      - name: Learn and Save
        run: |
          python test_models.py
      - name: Upload a Build Artifact - 4
        uses: actions/upload-artifact@v3.1.2
        with:
          name: save_result_test
          path: |
           result_new.txt
